### ISSUE TITLE
can't build soda...

### ISSUE THREAD

**Issue by leonqli** [elsevierlabs-os/soda#9]
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.eed3si9n#sbt-assembly;0.13.0: not found
[warn] 	:: com.typesafe.sbteclipse#sbteclipse-plugin;3.0.0: not found
[warn] 	:: com.earldouglas#xsbt-web-plugin;2.1.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::

**Comment by sujitpal** [comment]
Apologies for the delay in replying. Hopefully you have solved the problem yourself by now, looks like SBT dependencies in my development environment are obsolete and have been replaced with newer versions. So it works fine for me but not for someone who is building up an environment based on these dependencies. I don't use Scala/SBT enough nowadays to justify keeping on top of these changes, but based on your issue, I did the following upgrades.

1. [warn] :: com.eed3si9n#sbt-assembly;0.13.0: not found
According to [https://github.com/sbt/sbt-assembly/issues/245](https://github.com/sbt/sbt-assembly/issues/245), you can either add a repository or upgrade to 0.14.x, I have upgraded this to 0.14.6 (latest as of today, recommended for SBT 13.6+ I have SBT 13.7). Update is in the new project/plugins.sbt file.

2. [warn] :: com.typesafe.sbteclipse#sbteclipse-plugin;3.0.0: not found
According to [https://github.com/typesafehub/sbteclipse/issues/251](https://github.com/typesafehub/sbteclipse/issues/251), support for plugin configuration in project/plugins/ has been removed since 0.11.2. I originally had _all_ my SBT configuration in an external plugins.sbt in ~/.sbt/0.13/plugins/plugins.sbt, which seemed to work well for me. However, based on discussion in this issue, I have now a ~/.sbt/plugins/plugins.sbt which contains just these 2 lines. Also updated to latest version (as of today) of SBT-Eclipse plugin. Also you can drop this if you don't need to generate Eclipse artifacts for the project.

`
addSbtPlugin("com.typesafe.sbteclipse" % "sbteclipse-plugin" % "5.2.3")

`

3. [warn] :: com.earldouglas#xsbt-web-plugin;2.1.0: not found
According to [https://github.com/earldouglas/xsbt-web-plugin/issues/121](https://github.com/earldouglas/xsbt-web-plugin/issues/121), fix is to update version 0.4.0 which seemed like a typo, latest version according to website as of today is 4.0.1, so updated to that, fix is in the project/plugins.sbt file.

Also build.sbt has had a few lines removed because sbt-assembly no longer needs (or recognizes) these keywords.

Please try it out and close the issue if it works for you, or get back with what you see if not. If you've already fixed it, please share your solution here as well.

**Comment by sujitpal** [comment]
I have released a new version of SoDA which depends on current versions of Solr, SolrTextTagger, Scala and sbt. See [the change log](https://github.com/elsevierlabs-os/soda/blob/master/docs/changelog-v2.md) for details. Since these are current software, it is less likely to give you the problems you saw. 

Closing this, please reopen if this is still a problem with v2.
